# Data-specific parameters
dataset_name              : "chaotic_rnn"
run_name                  : "demo"
  
# Model parameters
g_dim                     : 20
u_dim                     : 20
factors_dim               : 2
g0_encoder_dim            : 20
c_encoder_dim             : 20
controller_dim            : 20
g0_prior_kappa            : 0.1
u_prior_kappa             : 0.1
keep_prob                 : 0.95
clip_val                  : 5.0
max_norm                  : 200

# Optimizer parameters
learning_rate             : 0.015
learning_rate_min         : 0.00001
learning_rate_decay       : 0.95
scheduler_on              : true
scheduler_patience        : 6
scheduler_cooldown        : 6
kl_weight_schedule_start  : 0
kl_weight_schedule_dur    : 2000
l2_weight_schedule_start  : 0
l2_weight_schedule_dur    : 2000
epsilon                   : 0.1
betas                     : !!python/tuple [0.9, 0.99]
l2_gen_scale              : 2000
l2_con_scale              : 0
